#!/bin/sh
#
# Manages a Presto node service
#
# chkconfig: 345 85 15
# description: Presto node
#
### BEGIN INIT INFO
# Provides:          presto
# Short-Description: presto node
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Should-Start:
# Should-Stop:
### END INIT INFO

SCRIPT_NAME=$0
ACTION_NAME=$1
SERVICE_NAME='presto'
echo Presto config directory is *${PRESTO_CONF_DIR}*
echo Presto home is *${PRESTO_HOME}*
NODE_PROPERTIES=${PRESTO_CONF_DIR}/node.properties
DATA_DIR=$(grep node.data-dir ${NODE_PROPERTIES} | cut -f2 -d=)
SERVER_LOG_FILE=$(grep node.server-log-file ${NODE_PROPERTIES} | cut -f2 -d=)
LAUNCHER_LOG_FILE=$(grep node.launcher-log-file ${NODE_PROPERTIES} | cut -f2 -d=)
CONFIGURATION="--launcher-config ${PRESTO_HOME}/bin/launcher.properties --data-dir ${DATA_DIR} --node-config ${NODE_PROPERTIES} \
              --jvm-config ${PRESTO_CONF_DIR}/jvm.config --config ${PRESTO_CONF_DIR}/config.properties \
              --launcher-log-file ${LAUNCHER_LOG_FILE:-/var/log/presto/launcher.log} \
              --server-log-file ${SERVER_LOG_FILE:-/var/log/presto/server.log}"


start () {
  echo "Starting ${SERVICE_NAME} "
  if [ -z "$JAVA_HOME" ]
  then
    echo "Warning: No value found for JAVA_HOME. Default Java will be used."
    ${PRESTO_HOME}/bin/launcher start ${CONFIGURATION}
  else
    PATH=${JAVA_HOME}/bin:$PATH ${PRESTO_HOME}/bin/launcher start ${CONFIGURATION}
  fi
  return $?
}

run () {
  echo "Starting ${SERVICE_NAME} "
  if [ -z "$JAVA_HOME" ]
  then
    echo "Warning: No value found for JAVA_HOME. Default Java will be used."
    ${PRESTO_HOME}/bin/launcher run ${CONFIGURATION}
  else
    PATH=${JAVA_HOME}/bin:$PATH ${PRESTO_HOME}/bin/launcher run ${CONFIGURATION}
  fi
  return $?
}

stop () {
  echo "Stopping ${SERVICE_NAME} "
  ${PRESTO_HOME}/bin/launcher stop ${CONFIGURATION}
  return $?
}

status () {
  echo "Getting status for ${SERVICE_NAME} "
  ${PRESTO_HOME}/bin/launcher status ${CONFIGURATION}
  return $?
}


restart () {
  ${PRESTO_HOME}/bin/launcher restart ${CONFIGURATION}
  return $?
}

usage () {
  echo $"Usage: ${SCRIPT_NAME} { run | start | stop | restart | status }"
  return 3
}

case "${ACTION_NAME}" in
  start ) start
    ;;
  run ) run
    ;;
  stop ) stop
    ;;
  restart ) restart
    ;;
  status ) status
    ;;
  * ) usage
esac

exit $?
